// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Validate environment variables
if (!SUPABASE_URL || SUPABASE_URL === '') {
  console.error('❌ Missing VITE_SUPABASE_URL in environment variables');
  console.error('Please add VITE_SUPABASE_URL to your .env file');
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === '' || SUPABASE_PUBLISHABLE_KEY === 'your_anon_key_here') {
  console.error('❌ Missing or invalid VITE_SUPABASE_PUBLISHABLE_KEY in environment variables');
  console.error('Please add VITE_SUPABASE_PUBLISHABLE_KEY to your .env file');
  console.error('Get your key from: https://supabase.com/dashboard/project/_/settings/api');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Log connection status
if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && SUPABASE_PUBLISHABLE_KEY !== 'your_anon_key_here') {
  console.log('✅ Supabase client initialized');
  console.log('📍 URL:', SUPABASE_URL);
  console.log('🔑 API Key:', SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...');
  
  // Check if API key matches the project URL (only for JWT format keys)
  try {
    // Only check JWT format keys (start with eyJ)
    if (SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ')) {
      const keyPayload = JSON.parse(atob(SUPABASE_PUBLISHABLE_KEY.split('.')[1]));
      const keyProjectRef = keyPayload.ref;
      const urlProjectRef = SUPABASE_URL.match(/https:\/\/([^.]+)\.supabase\.co/)?.[1];
      
      if (keyProjectRef && urlProjectRef && keyProjectRef !== urlProjectRef) {
        console.error('❌ API KEY MISMATCH ERROR!');
        console.error(`   API Key is for project: ${keyProjectRef}`);
        console.error(`   But URL is for project: ${urlProjectRef}`);
        console.error('   These must match! Please update your API key in .env file');
        console.error('   Get your key from: https://supabase.com/dashboard/project/' + urlProjectRef + '/settings/api');
      }
    } else {
      // New format key (sb_publishable_...)
      console.log('📝 Using new API key format');
    }
  } catch (e) {
    // Key parsing failed, but continue anyway - might be new format
  }
  
  // Test connection
  supabase.auth.getSession().then(({ data, error }) => {
    if (error) {
      if (error.message.includes('Invalid API key') || error.message.includes('JWT')) {
        console.error('❌ INVALID API KEY!');
        console.error('   Please check your .env file and get the correct API key');
        console.error('   See FIX_API_KEY.md for instructions');
      } else {
        console.warn('⚠️ Supabase connection test failed:', error.message);
      }
    } else {
      console.log('✅ Supabase connection test successful');
    }
  }).catch(err => {
    if (err.message?.includes('Invalid API key')) {
      console.error('❌ INVALID API KEY!');
      console.error('   See FIX_API_KEY.md for instructions to fix this');
    } else {
      console.warn('⚠️ Supabase connection error:', err);
    }
  });
} else {
  console.error('❌ Supabase client initialized with missing or placeholder credentials');
  console.error('Please check your .env file and ensure both VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set');
}